---
name: Build Docker images

on:
  pull_request:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        image: [latex, dmrconfig, ppp]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: tzermias/${{ matrix.image }}:latest

      - name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: tzermias/${{ matrix.image }}
          readme-filepath: ./${{ matrix.image }}/README.md

# vi: ts=2 sts=2 et sw=2
