---
name: Build Docker images

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image.
        run: docker build -t latex latex/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        image: [latex, dmrconfig]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./${{ matrix.image }}/Dockerfile
          push: true
          tags: tzermias/${{ matrix.image }}:latest

# vi: ts=2 sts=2 et sw=2
